// Package render turns a plan into text: a Markdown block for the repository,
// a Mermaid diagram GitHub draws natively, and an ASCII tree for the terminal.
//
// Every function here is pure — a tree goes in, a string comes out. File
// handling lives in the CLI layer. That split is what lets the golden tests
// compare whole diagrams without touching the disk.
package render

import (
	"fmt"
	"strings"

	"github.com/SergeyLubivui-dev/devtree/internal/tree"
)

// Markers fence the generated region. Everything between them is rewritten on
// every render; everything outside is left exactly as the author wrote it,
// which is what makes embedding the diagram in an existing README safe.
const (
	MarkerBegin = "<!-- devtree:begin -->"
	MarkerEnd   = "<!-- devtree:end -->"
)

// Block assembles the whole generated region: heading, progress bar, diagram,
// legend, and the link table.
func Block(t *tree.Tree) string {
	var b strings.Builder

	b.WriteString(MarkerBegin + "\n")
	b.WriteString("<!-- Generated by devtree. Do not edit by hand: edit .devtree/tree.yaml instead. -->\n\n")

	title := t.Project
	if title == "" {
		title = "Development tree"
	}
	fmt.Fprintf(&b, "## 🌳 %s\n\n", title)

	done, total := t.Totals()
	fmt.Fprintf(&b, "%s **%d / %d** tasks done\n\n", ProgressBar(done, total), done, total)

	b.WriteString(Mermaid(t))
	b.WriteString("\n")
	b.WriteString(Legend())
	b.WriteString(LinkTable(t))
	b.WriteString("\n" + MarkerEnd)

	return b.String()
}

// barWidth is a compromise: wide enough to read at a glance, narrow enough to
// sit on one line next to the counts on a phone.
const barWidth = 20

// ProgressBar draws a filled/empty bar with block characters, which render
// identically everywhere Markdown does — no images, no SVG, no cache busting.
func ProgressBar(done, total int) string {
	if total <= 0 {
		return strings.Repeat("░", barWidth)
	}
	filled := done * barWidth / total
	if filled > barWidth {
		filled = barWidth
	}
	return strings.Repeat("█", filled) + strings.Repeat("░", barWidth-filled)
}

// Legend explains the glyphs. It is generated from the status list, so adding
// a status can never leave the legend out of date.
func Legend() string {
	parts := make([]string, 0, len(tree.Statuses))
	for _, s := range tree.Statuses {
		parts = append(parts, s.Icon()+" "+s.Label())
	}
	return "> " + strings.Join(parts, " · ") + "\n"
}

// LinkTable lists the branches, issues, and pull requests behind the diagram.
//
// It exists because GitHub's Mermaid renderer ignores `click` directives for
// security reasons, so a node in the diagram cannot itself be a link. Rather
// than pretend otherwise, the links get their own collapsed table underneath.
func LinkTable(t *tree.Tree) string {
	type row struct{ id, title, status, link string }

	var rows []row
	for _, n := range t.Nodes {
		var link string
		switch {
		case n.PR != "":
			link = repoLink(t, "pull", n.PR)
		case n.Issue != "":
			link = repoLink(t, "issues", n.Issue)
		case n.Branch != "":
			link = "`" + n.Branch + "`"
		default:
			continue // nothing to link to
		}
		rows = append(rows, row{n.ID, n.Title, n.Status.Icon() + " " + n.Status.Label(), link})
	}
	if len(rows) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n<details>\n<summary>Branches, issues, and pull requests</summary>\n\n")
	b.WriteString("| id | Task | Status | Link |\n|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.id, escapePipe(r.title), r.status, r.link)
	}
	b.WriteString("\n</details>\n")
	return b.String()
}

// repoLink prefers the configured repo URL and falls back to a relative link.
// The `../../issues/12` form is what GitHub itself uses: from a file in the
// repository root it resolves to the issue, with no hostname baked in, so the
// plan survives being forked or moved to another host.
func repoLink(t *tree.Tree, kind, number string) string {
	if t.Repo != "" {
		return fmt.Sprintf("[#%s](%s/%s/%s)", number, t.Repo, kind, number)
	}
	return fmt.Sprintf("[#%s](../../%s/%s)", number, kind, number)
}

// escapePipe keeps a title containing "|" from splitting a table cell.
func escapePipe(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
